//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftyBot open source project
//
// Copyright (c) 2016 - 2018 Fabrizio Brancati
// Licensed under The MIT License (MIT)
//
// See LICENSE for license information
//
//===----------------------------------------------------------------------===//
//
// ButtonTests+XCTest.swift
//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension ButtonTests {
    static var allTests : [(String, (ButtonTests) -> () throws -> Void)] {
        return [
            ("testInitWebURL", testInitWebURL),
            ("testInitPostback", testInitPostback),
        ]
    }
}

