//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftyBot open source project
//
// Copyright (c) 2016 - 2018 Fabrizio Brancati
// Licensed under The MIT License (MIT)
//
// See LICENSE for license information
//
//===----------------------------------------------------------------------===//
//
// LinuxMain.swift
//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

#if os(Linux) || os(FreeBSD)
    @testable import BotTests
    @testable import HelpersTests
    @testable import TelegramTests

    XCTMain([
        testCase(CommandTests.allTests),
        testCase(StringExtensionsTests.allTests),
        testCase(TelegramRoutesTests.allTests),
    ])
#endif
